In [32]:
SELECT hours_studied, AVG(exam_score) AS avg_exam_score
FROM student_performance
WHERE hours_studied > 10
  AND extracurricular_activities = 'Yes'
GROUP BY hours_studied
ORDER BY hours_studied DESC;

    hours_studied  avg_exam_score
0              43       78.000000
1              39       75.000000
2              38       73.500000
3              37       73.000000
4              36       70.428571
5              35       72.312500
6              34       71.187500
7              33       70.333333
8              32       71.325000
9              31       70.553191
10             30       71.432836
11             29       70.256098
12             28       69.825688
13             27       69.776860
14             26       68.801370
15             25       69.000000
16             24       68.483871
17             23       68.207469
18             22       67.721519
19             21       67.710425
20             20       67.218638
21             19       67.211765
22             18       67.024000
23             17       66.401826
24             16       66.586047
25             15       65.901099
26             14       65.862275
27             13       64.976190
28             12       64.966102
29             11       65.145833

In [33]:
select 
	case when hours_studied between 1 and 5 then '1-5 hours'
	when hours_studied between 6 and 10 then '6-10 hours'
	when hours_studied between 11 and 15 then '11-15 hours'
	else '16+ hours' end as hours_studied_range,
	avg(exam_score) as avg_exam_score
from student_performance
group by hours_studied_range
order by avg(exam_score) desc;

  hours_studied_range  avg_exam_score
0           16+ hours       67.923363
1         11-15 hours       65.204386
2          6-10 hours       64.225490
3           1-5 hours       62.627119

In [34]:
SELECT 
    Attendance, 
    Hours_Studied, 
    Sleep_Hours, 
    Tutoring_Sessions, 
    DENSE_RANK() OVER (ORDER BY Exam_Score DESC) AS exam_rank
FROM student_performance
ORDER BY exam_rank ASC
LIMIT 30;

    attendance  hours_studied  sleep_hours  tutoring_sessions  exam_rank
0           98             27            6                  5          1
1           89             18            4                  3          2
2           90             14            8                  4          3
3           83             23            4                  1          3
4           96             28            4                  1          4
5           90             28            9                  0          4
6           83             16            8                  2          4
7           83             15            7                  2          5
8           74             21            6                  1          5
9           99             25            7                  0          5
10          93             18            7                  2          6
11          90             18            6                  1          7
12          67             21            6                  1          7
13          96             24            6                  2          8
14          98             25            7                  1          8
15          76             29            8                  2          8
16          90             19            5                  0          8
17          69             26            7                  0          9
18          73             25            7                  2          9
19          88              1            4                  3         10
20          69             31            7                  2         10
21          70             21            9                  1         11
22          77             14            6                  1         12
23          92             21            9                  2         12
24          70             19            7                  0         12
25          86             18            8                  2         13
26          98             30            9                  1         13
27          62             11            7                  3         13
28          71             11            8                  1         14
29          69              7            8                  1         14